CREATE OR REPLACE TABLE "EL_MATILLION_RAW"."RAW_CSV"."dim_current_loss_run" (
    "claim_number" NUMBER,
    "prior_claim_number" TEXT,
    "date_of_loss_claim_desc" TEXT,
    "claimant_name" TEXT,
    "coverage" TEXT,
    "birth_date" TEXT,
    "sex" TEXT,
    "claimant_status_desc" TEXT,
    "litigated" BOOLEAN,
    "litigation_status" TEXT,
    "state_code" TEXT,
    "incident_claims_made_date" TIMESTAMP_NTZ,
    "report_date" TIMESTAMP_NTZ,
    "closed_date" TIMESTAMP_NTZ,
    "reopened_date" TIMESTAMP_NTZ,
    "claimant_type_desc" TEXT,
    "ulae_expense_amount" NUMBER(38, 2),
    "ulae_reserves" NUMBER(38, 2),
    "ulae_incurred" NUMBER(38, 2),
    "paid_indemnity" NUMBER(38, 2),
    "paid_expense" NUMBER(38, 2),
    "paid" NUMBER(38, 2),
    "incurred_indemnity" NUMBER(38, 2),
    "incurred_expense" NUMBER(38, 2),
    "incurred" NUMBER(38, 2),
    "outstanding_indemnity" NUMBER(38, 2),
    "outstanding_expense" NUMBER(38, 2),
    "outstanding" NUMBER(38, 2),
    "client_code" NUMBER,
    "insurer_name" TEXT,
    "insured_name1" TEXT,
    "policy_number" TEXT,
    "policy_period_desc" TEXT,
    "policy_year" TEXT,
    "closed_claimant" BOOLEAN,
    "open_claimant" BOOLEAN,
    "closed_lit_claimant" BOOLEAN,
    "open_lit_claimant" BOOLEAN
);